### ISSUE TITLE
Add report page

### ISSUE THREAD

**Issue by oscarsuen** [lefriedberg/CS490-lib#3]
"Also, create a place where the admin can go to create reports, for example, run a report to see how many books are in the system, how many members are in the system, how many books are checked out and to whom, etc. (let them choose what kind of report they want to run)"

**Comment by lefriedberg** [comment]
HTML exists,

write php

We can't track returns because we delete loans upon return

**Comment by lefriedberg** [comment]
There's no form in the report page.

**Comment by xstephenhu98** [comment]
Not yet

**Comment by oscarsuen** [comment]
done
